In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

In [4]:
df = pd.read_csv('data/training.1600000.processed.noemoticon.csv',
                  encoding='latin-1', header=None)
df = df[[0,5]]
df.columns = ['polarity', 'text']
df.head()

   polarity                                               text
0         0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1         0  is upset that he can't update his Facebook by ...
2         0  @Kenichan I dived many times for the ball. Man...
3         0    my whole body feels itchy and like its on fire
4         0  @nationwideclass no, it's not behaving at all....

In [6]:
df = df[df.polarity !=2]
df['polarity'] = df['polarity'].map({0:0, 4:1})
df['polarity'].value_counts()

polarity
0    800000
1    800000
Name: count, dtype: int64

In [7]:
def clean_text(text):
    return text.lower()
df ['clean_text'] = df['text'].apply(clean_text)

df[['text', 'clean_text']].head()

                                                text                                         clean_text
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  @switchfoot http://twitpic.com/2y1zl - awww, t...
1  is upset that he can't update his Facebook by ...  is upset that he can't update his facebook by ...
2  @Kenichan I dived many times for the ball. Man...  @kenichan i dived many times for the ball. man...
3    my whole body feels itchy and like its on fire     my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....  @nationwideclass no, it's not behaving at all....

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['polarity'],
    test_size=0.2,
    random_state=42
)
len(X_train), len(X_test)

(1280000, 320000)

In [9]:
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

X_test_tfidf.shape, X_train_tfidf.shape

((320000, 5000), (1280000, 5000))

In [10]:
bnb = BernoulliNB()
bnb.fit(X_train_tfidf, y_train)
bnb_pred = bnb.predict(X_test_tfidf)

print("bernouilli naive bayes accuracy:", accuracy_score(y_test, bnb_pred))
print("\nbernuoilliNB classification report:\n", classification_report(y_test, bnb_pred))

bernouilli naive bayes accuracy: 0.766478125

bernuoilliNB classification report:
               precision    recall  f1-score   support

           0       0.77      0.75      0.76    159494
           1       0.76      0.78      0.77    160506

    accuracy                           0.77    320000
   macro avg       0.77      0.77      0.77    320000
weighted avg       0.77      0.77      0.77    320000